export { Login } from './Login'
export { HomePage } from './HomePage'
export { NotFoundPage } from './NotFoundPage'
export { PetPage } from './PetPage'
export { ServicesPage } from './ServicesPage'
export { ProductsPage } from './ProductsPage'
export { AppointmentsPage } from './AppointmentsPage'
export { UserPage } from './UserPage'
export { ContactUsPage } from './ContactUsPage'
export { AboutProject } from './AboutProject'
export { Register } from './Register'

export { Dev } from './Dev'
